FROM ghcr.io/puppeteer/puppeteer:24.4.0

# Switch to root user to install packages
USER root

# Install Chromium instead of Google Chrome
RUN apt update && apt install -y chromium

# Switch back to non-root user for security
USER pptruser

# Set environment variables for Puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Set working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the app files
COPY . .

CMD ["node", "dist/index.js"]


